### ISSUE TITLE
Does this body of work consider SharePoint ACLs? 

### ISSUE THREAD

**Issue by jharbieh-microsoft** [ms-us-rcg-cloud-innovation/sharepoint-to-blob-indexing#1]
Hi there team! 

I couldn't find a reference in the codebase here that considers SharePoint File ACLs. [Authorization, users, groups, and the object model in SharePoint](https://learn.microsoft.com/en-us/sharepoint/dev/general-development/authorization-users-groups-and-the-object-model-in-sharepoint) We have multiple customers wanting to use this workaround; however, we need to ensure that when a User logs on to use the Chat interface, they are not seeing content from files they are not supposed to have access to. 

Please advise. 

Thanks!

**Comment by jharbieh-microsoft** [comment]
@sethsteenken see above when you get a chance. Hit me up for details. Thanks!

**Comment by sethsteenken** [comment]
Hey @jharbieh-microsoft - currently this solution does not support the ACLs from Sharepoint. It will monitor a given List in Sharepoint and have documents and pages in that list indexed into Azure AI Search. It is assumed users searching against that index are able to view and search those items.

The ACLs create very tricky barriers when attempting to filter results from AI Search. There may be options around storing a form of ACLs on the individual indexed items and then filtering on those per search, but that's a complexity that may be outside the scope of this project. I would LOVE to explore that path, but it's not something that's being pursued here.

**Comment by jharbieh-microsoft** [comment]
Thank you for the clarification on this item. I agree. How to comply with SharePoint ACLs when the File/Object has left the building. Thanks @sethsteenken
